import { Product } from "../types/Product.type";

export const SampleProducts: Product[] = [
  {
    id: '1',
    image: 'https://picsum.photos/200',
    name: "COKE 1L",
    stock: 5,
    price: 48,
  },
  {
    id: '2',
    image: 'https://picsum.photos/200',
    name: "COKE 8oz",
    stock: 10,
    price: 13,
  },
  {
    id: '3',
    image: 'https://picsum.photos/200',
    name: "COKE 1.5L",
    stock: 5,
    price: 75,
  },
  {
    id: '4',
    image: 'https://picsum.photos/200',
    name: "SPRITE 1.5L",
    stock: 2,
    price: 75,
  },
  {
    id: '5',
    image: 'https://picsum.photos/200',
    name: "ROYAL 1.5L",
    stock: 2,
    price: 75,
  },
  {
    id: '6',
    image: 'https://picsum.photos/200',
    name: "ZEST-O Orange 200ml",
    stock: 10,
    price: 11,
  },
  {
    id: '7',
    image: 'https://picsum.photos/200',
    name: "STING ENERGY DRINK STRAWBERRY",
    stock: 5,
    price: 24,
  },
  {
    id: '8',
    image: 'https://picsum.photos/200',
    name: "COBRA ENERGY DRINK",
    stock: 5,
    price: 26,
  },
  {
    id: '9',
    image: 'https://picsum.photos/200',
    name: "ROYAL ORANGE SWAKTO 190ML",
    stock: 20,
    price: 15,
  },
  {
    id: '10',
    image: 'https://picsum.photos/200',
    name: "COKE SWAKTO 190ML",
    stock: 20,
    price: 15,
  },
  {
    id: '11',
    image: 'https://picsum.photos/200',
    name: "SPRITE SWAKTO 190ML",
    stock: 20,
    price: 15,
  },
  {
    id: '12',
    image: 'https://picsum.photos/200',
    name: "MINUTE MAID FRESH ORANGE 180-200ML",
    stock: 9,
    price: 15,
  },
  {
    id: '13',
    image: 'https://picsum.photos/200',
    name: "YAKULT 5S 80ML",
    stock: 15,
    price: 15,
  },
  {
    id: '14',
    image: 'https://picsum.photos/200',
    name: "KULAFU",
    stock: 6,
    price: 48,
  },
  {
    id: '15',
    image: 'https://picsum.photos/200',
    name: "NATURE'S SPRING PURIFIED DRINKING 1000ML",
    stock: 5,
    price: 25,
  },
  {
    id: '16',
    image: 'https://picsum.photos/200',
    name: "NATURE'S SPRING PURIFIED DRINKING 500ML",
    stock: 5,
    price: 15,
  },
  {
    id: '17',
    image: 'https://picsum.photos/200',
    name: "VITAMILK DOUBLE CHOCO SHAKE",
    stock: 2,
    price: 35,
  },
  {
    id: '18',
    image: 'https://picsum.photos/200',
    name: "VITAMILK CHOCO SHAKE",
    stock: 2,
    price: 35,
  },
  {
    id: '19',
    image: 'https://picsum.photos/200',
    name: "VITAMILK BANANA",
    stock: 3,
    price: 35,
  },
  {
    id: '20',
    image: 'https://picsum.photos/200',
    name: "TANG DALANDAN",
    stock: 10,
    price: 23,
  },
  {
    id: '21',
    image: 'https://picsum.photos/200',
    name: "TANG ORANGE",
    stock: 10,
    price: 23,
  },
  {
    id: '22',
    image: 'https://picsum.photos/200',
    name: "SUNPRIDE TOCINO MIX",
    stock: 4,
    price: 51,
  },
  {
    id: '23',
    image: 'https://picsum.photos/200',
    name: "BIODERM BLOOM PINK",
    stock: 6,
    price: 19,
  },
  {
    id: '24',
    image: 'https://picsum.photos/200',
    name: "SAFEGUARD WHITE ULTRA",
    stock: 6,
    price: 23,
  },
  {
    id: '25',
    image: 'https://picsum.photos/200',
    name: "GENTLE BUDS PL WHITE",
    stock: 3,
    price: 16,
  },
  {
    id: '26',
    image: 'https://picsum.photos/200',
    name: "BIODERM FRESH GREEN 120",
    stock: 6,
    price: 20,
  },
  {
    id: '27',
    image: 'https://picsum.photos/200',
    name: "SILKA PAPAYA FACIAL CLEANSER",
    stock: 2,
    price: 35,
  },
  {
    id: '28',
    image: 'https://picsum.photos/200',
    name: "SILKA PAPAYA SOAP",
    stock: 2,
    price: 42,
  },
  {
    id: '29',
    image: 'https://picsum.photos/200',
    name: "SILKA PAPAYA SOAP 65G",
    stock: 6,
    price: 20,
  },
  {
    id: '30',
    image: 'https://picsum.photos/200',
    name: "Coke 8 oz",
    stock: 20,
    price: 13,
  },
  {
    id: '31',
    image: 'https://picsum.photos/200',
    name: "REXONA DEOLTN PWDR DRY 360/3ML",
    stock: 3,
    price: 8,
  },
  {
    id: '32',
    image: 'https://picsum.photos/200',
    name: "REXONA DEOLTN PASSION 360/3ML",
    stock: 3,
    price: 8,
  },
  {
    id: '33',
    image: 'https://picsum.photos/200',
    name: "LORD TAJAMZ RAZOR TWIN BLADE(YELLOW)",
    stock: 6,
    price: 23,
  },
  {
    id: '34',
    image: 'https://picsum.photos/200',
    name: "SNOWBEAR",
    stock: 20,
    price: 1.25,
  },
  {
    id: '35',
    image: 'https://picsum.photos/200',
    name: "COCO ANIMALS LOLLIPOP",
    stock: 30,
    price: 7,
  },
  {
    id: '36',
    image: 'https://picsum.photos/200',
    name: "MAXX HONEY LEMON CANDY",
    stock: 20,
    price: 1.25,
  },
  {
    id: '37',
    image: 'https://picsum.photos/200',
    name: "KENDI MINT",
    stock: 20,
    price: 1.25,
  },
  {
    id: '38',
    image: 'https://picsum.photos/200',
    name: "HOLIDAY CARNE NORTE (GAMAY)",
    stock: 20,
    price: 35,
  },
  {
    id: '39',
    image: 'https://picsum.photos/200',
    name: "HOLIDAY BEEF LOAF",
    stock: 20,
    price: 25,
  },
  {
    id: '40',
    image: 'https://picsum.photos/200',
    name: "MEGA SARDINES RED",
    stock: 20,
    price: 30,
  },
  {
    id: '41',
    image: 'https://picsum.photos/200',
    name: "YOUNG’S TOWN SARDINES N TOMATO SAUCE RED",
    stock: 20,
    price: 27,
  },
  {
    id: '42',
    image: 'https://picsum.photos/200',
    name: "SENORITA SARDINES GREEN",
    stock: 20,
    price: 28,
  },
  {
    id: '43',
    image: 'https://picsum.photos/200',
    name: "CENTURY TUNA JR HOT N SPICY",
    stock: 20,
    price: 44,
  },
  {
    id: '44',
    image: 'https://picsum.photos/200',
    name: "CENTURY TUNA FLAKES N OIL JR",
    stock: 20,
    price: 43,
  },
  {
    id: '45',
    image: 'https://picsum.photos/200',
    name: "YOUNG’S TOWN SARDINES GREEN",
    stock: 20,
    price: 27,
  },
  {
    id: '46',
    image: 'https://picsum.photos/200',
    name: "HOLIDAY CORNED BEEF 215G (DAKO)",
    stock: 20,
    price: 57,
  },
  {
    id: '47',
    image: 'https://picsum.photos/200',
    name: "FIESTA BEEF LOAF 150G (GAMAY)",
    stock: 20,
    price: 27,
  },
  {
    id: '48',
    image: 'https://picsum.photos/200',
    name: "FIESTA BEEF LOAF 215G (DAKO)",
    stock: 20,
    price: 36,
  },
  {
    id: '49',
    image: 'https://picsum.photos/200',
    name: "MIGHTY RED",
    stock: 20,
    price: 8,
  },
  {
    id: '50',
    image: 'https://picsum.photos/200',
    name: "MIGHTY WHITE",
    stock: 20,
    price: 8,
  },
  {
    id: '51',
    image: 'https://picsum.photos/200',
    name: "MARLBORO RED",
    stock: 20,
    price: 10,
  },
  {
    id: '52',
    image: 'https://picsum.photos/200',
    name: "MARLBORO ICE BLAST",
    stock: 20,
    price: 10,
  },
  {
    id: '53',
    image: 'https://picsum.photos/200',
    name: "WINSTON",
    stock: 20,
    price: 9,
  },
  {
    id: '54',
    image: 'https://picsum.photos/200',
    name: "BEARBRAND PWDR MLK",
    stock: 20,
    price: 13,
  },
  {
    id: '55',
    image: 'https://picsum.photos/200',
    name: "GREAT TASTE WHITE SINGLE",
    stock: 20,
    price: 10,
  },
  {
    id: '56',
    image: 'https://picsum.photos/200',
    name: "BIRCH TREE FORTIFIED MILK DRINK",
    stock: 20,
    price: 12,
  },
  {
    id: '57',
    image: 'https://picsum.photos/200',
    name: "EGG (ITLOG)",
    stock: 20,
    price: 10,
  },
]